// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/ads" | "/admin/categories" | "/admin/categories/[id]" | "/admin/categories/create" | "/admin/couriers" | "/admin/couriers/[id]" | "/admin/couriers/create" | "/admin/dashboard" | "/admin/gallery" | "/admin/legal" | "/admin/messages" | "/admin/my-company" | "/admin/my-subscription" | "/admin/orders" | "/admin/orders/[order_id]" | "/admin/plans" | "/admin/plans/[id]" | "/admin/plans/create" | "/admin/products" | "/admin/products/[id]" | "/admin/products/create" | "/admin/profile" | "/admin/sell-faq" | "/admin/sellers" | "/admin/sellers/[id]" | "/admin/sellers/create" | "/admin/services" | "/admin/services/[id]" | "/admin/services/create" | "/admin/settings/configuracion" | "/admin/settings/shipping" | "/admin/stats" | "/admin/subcategories" | "/admin/subcategories/[id]" | "/admin/subcategories/create" | "/admin/subscriptions" | "/admin/suppliers" | "/admin/suppliers/[id]" | "/admin/suppliers/create" | "/admin/support" | "/admin/support/[id]" | "/admin/support/unassigned" | "/admin/users" | "/admin/users/[id]" | "/admin/users/create" | "/admin/welcome" | "/cart" | "/categorias/[slug]" | "/centro-de-ayuda" | "/checkout/[order_id]" | "/client/become-supplier" | "/client/cart" | "/client/favorites" | "/client/messages" | "/client/notifications" | "/client/orders" | "/client/orders/[order_id]" | "/client/profile" | "/contacto" | "/empresas/[slug]" | "/login" | "/mis-pedidos" | "/nosotros" | "/orders/[orderId]" | "/payment-info" | "/politicas-de-privacidad" | "/product/[slug]" | "/product/[slug]/similar" | "/recomendados" | "/register" | "/sell" | "/sell/register" | "/servicios/[id]" | "/supplier/messages" | "/support" | "/support/[id]" | "/terminos-y-condiciones"
type AppRouteHandlerRoutes = "/api/[...path]" | "/api/login/access-token" | "/api/login/refresh-token" | "/api/products/recommended/supplier/[id]" | "/proxy/[...path]" | "/static/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/cart" | "/client" | "/empresas/[slug]" | "/login" | "/register"
type RedirectRoutes = never
type RewriteRoutes = "/api/backend/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/ads": {}
  "/admin/categories": {}
  "/admin/categories/[id]": { "id": string; }
  "/admin/categories/create": {}
  "/admin/couriers": {}
  "/admin/couriers/[id]": { "id": string; }
  "/admin/couriers/create": {}
  "/admin/dashboard": {}
  "/admin/gallery": {}
  "/admin/legal": {}
  "/admin/messages": {}
  "/admin/my-company": {}
  "/admin/my-subscription": {}
  "/admin/orders": {}
  "/admin/orders/[order_id]": { "order_id": string; }
  "/admin/plans": {}
  "/admin/plans/[id]": { "id": string; }
  "/admin/plans/create": {}
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/products/create": {}
  "/admin/profile": {}
  "/admin/sell-faq": {}
  "/admin/sellers": {}
  "/admin/sellers/[id]": { "id": string; }
  "/admin/sellers/create": {}
  "/admin/services": {}
  "/admin/services/[id]": { "id": string; }
  "/admin/services/create": {}
  "/admin/settings/configuracion": {}
  "/admin/settings/shipping": {}
  "/admin/stats": {}
  "/admin/subcategories": {}
  "/admin/subcategories/[id]": { "id": string; }
  "/admin/subcategories/create": {}
  "/admin/subscriptions": {}
  "/admin/suppliers": {}
  "/admin/suppliers/[id]": { "id": string; }
  "/admin/suppliers/create": {}
  "/admin/support": {}
  "/admin/support/[id]": { "id": string; }
  "/admin/support/unassigned": {}
  "/admin/users": {}
  "/admin/users/[id]": { "id": string; }
  "/admin/users/create": {}
  "/admin/welcome": {}
  "/api/[...path]": { "path": string[]; }
  "/api/backend/[[...path]]": { "path"?: string[]; }
  "/api/login/access-token": {}
  "/api/login/refresh-token": {}
  "/api/products/recommended/supplier/[id]": { "id": string; }
  "/cart": {}
  "/categorias/[slug]": { "slug": string; }
  "/centro-de-ayuda": {}
  "/checkout/[order_id]": { "order_id": string; }
  "/client": {}
  "/client/become-supplier": {}
  "/client/cart": {}
  "/client/favorites": {}
  "/client/messages": {}
  "/client/notifications": {}
  "/client/orders": {}
  "/client/orders/[order_id]": { "order_id": string; }
  "/client/profile": {}
  "/contacto": {}
  "/empresas/[slug]": { "slug": string; }
  "/login": {}
  "/mis-pedidos": {}
  "/nosotros": {}
  "/orders/[orderId]": { "orderId": string; }
  "/payment-info": {}
  "/politicas-de-privacidad": {}
  "/product/[slug]": { "slug": string; }
  "/product/[slug]/similar": { "slug": string; }
  "/proxy/[...path]": { "path": string[]; }
  "/recomendados": {}
  "/register": {}
  "/sell": {}
  "/sell/register": {}
  "/servicios/[id]": { "id": string; }
  "/static/[...path]": { "path": string[]; }
  "/supplier/messages": {}
  "/support": {}
  "/support/[id]": { "id": string; }
  "/terminos-y-condiciones": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/cart": never
  "/client": never
  "/empresas/[slug]": never
  "/login": never
  "/register": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
