// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/couriers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/couriers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/couriers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/couriers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/couriers/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/couriers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/couriers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/couriers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/couriers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/admin/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/legal">> = Specific
  const handler = {} as typeof import("../../src/app/admin/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/my-company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/my-company">> = Specific
  const handler = {} as typeof import("../../src/app/admin/my-company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/my-subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/my-subscription">> = Specific
  const handler = {} as typeof import("../../src/app/admin/my-subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/[order_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[order_id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/[order_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/plans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/plans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/plans/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/plans/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans">> = Specific
  const handler = {} as typeof import("../../src/app/admin/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/sell-faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sell-faq">> = Specific
  const handler = {} as typeof import("../../src/app/admin/sell-faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/sellers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sellers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/sellers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/sellers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sellers/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/sellers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/sellers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sellers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/sellers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/services/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/services/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/services/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/services/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/shipping">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/admin/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/subcategories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subcategories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/subcategories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/subcategories/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subcategories/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/subcategories/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/subcategories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subcategories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/subcategories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/suppliers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/suppliers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/suppliers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suppliers/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/suppliers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support/unassigned/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support/unassigned">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support/unassigned/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/welcome">> = Specific
  const handler = {} as typeof import("../../src/app/admin/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/categorias/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categorias/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/categorias/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/centro-de-ayuda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/centro-de-ayuda">> = Specific
  const handler = {} as typeof import("../../src/app/centro-de-ayuda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/[order_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/[order_id]">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/[order_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/become-supplier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/become-supplier">> = Specific
  const handler = {} as typeof import("../../src/app/client/become-supplier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/cart">> = Specific
  const handler = {} as typeof import("../../src/app/client/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/client/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/messages">> = Specific
  const handler = {} as typeof import("../../src/app/client/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/client/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/orders/[order_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/orders/[order_id]">> = Specific
  const handler = {} as typeof import("../../src/app/client/orders/[order_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/orders">> = Specific
  const handler = {} as typeof import("../../src/app/client/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../src/app/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/empresas/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empresas/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/empresas/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mis-pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis-pedidos">> = Specific
  const handler = {} as typeof import("../../src/app/mis-pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nosotros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nosotros">> = Specific
  const handler = {} as typeof import("../../src/app/nosotros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment-info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment-info">> = Specific
  const handler = {} as typeof import("../../src/app/payment-info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/politicas-de-privacidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/politicas-de-privacidad">> = Specific
  const handler = {} as typeof import("../../src/app/politicas-de-privacidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/product/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/[slug]/similar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[slug]/similar">> = Specific
  const handler = {} as typeof import("../../src/app/product/[slug]/similar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recomendados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recomendados">> = Specific
  const handler = {} as typeof import("../../src/app/recomendados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sell">> = Specific
  const handler = {} as typeof import("../../src/app/sell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sell/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sell/register">> = Specific
  const handler = {} as typeof import("../../src/app/sell/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servicios/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicios/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/servicios/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supplier/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplier/messages">> = Specific
  const handler = {} as typeof import("../../src/app/supplier/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terminos-y-condiciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminos-y-condiciones">> = Specific
  const handler = {} as typeof import("../../src/app/terminos-y-condiciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/login/access-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login/access-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/login/access-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/login/refresh-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login/refresh-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/login/refresh-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/recommended/supplier/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/recommended/supplier/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/recommended/supplier/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/static/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/static/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/static/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/client">> = Specific
  const handler = {} as typeof import("../../src/app/client/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/empresas/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/empresas/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/empresas/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
