"use client";

import { useState } from "react";
import { useAuthStore } from "@/store/useAuthStore";
import { useRouter } from "next/navigation";
import { 
  Loader2, 
  CheckCircle, 
  X, 
  Smartphone, 
  Laptop, 
  Headphones, 
  Shirt, 
  Home, 
  Car, 
  Wrench, 
  Watch, 
  Camera, 
  Gamepad, 
  Music, 
  Book, 
  Coffee, 
  Utensils, 
  Gift, 
  ShoppingBag, 
  Tag, 
  Grid, 
  Layers, 
  Package, 
  Zap, 
  Activity, 
  Heart, 
  Smile
} from "lucide-react";
import { fetchWithAuth } from "@/lib/api";
import { cn } from "@/lib/utils";

// List of available icons for selection
const AVAILABLE_ICONS = [
  "Smartphone", "Laptop", "Headphones", "Shirt", "Home", "Car", 
  "Wrench", "Watch", "Camera", "Gamepad", "Music", "Book", 
  "Coffee", "Utensils", "Gift", "ShoppingBag", "Tag", "Grid", 
  "Layers", "Package", "Zap", "Activity", "Heart", "Smile"
];

// Map string names to components
const ICON_COMPONENTS: Record<string, any> = {
  Smartphone, Laptop, Headphones, Shirt, Home, Car, 
  Wrench, Watch, Camera, Gamepad, Music, Book, 
  Coffee, Utensils, Gift, ShoppingBag, Tag, Grid, 
  Layers, Package, Zap, Activity, Heart, Smile
};

interface Category {
  id: number;
  name: string;
  description: string;
  icon: string | null;
  is_active: boolean;
  slug: string;
}

interface CategoryFormData {
  name: string;
  description: string;
  icon: string | null;
  is_active: boolean;
}

const initialFormData: CategoryFormData = {
  name: "",
  description: "",
  icon: null,
  is_active: true,
};

interface CategoryFormProps {
  initialData?: Category;
}

export default function CategoryForm({ initialData }: CategoryFormProps) {
  const router = useRouter();
  const { token } = useAuthStore();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [formData, setFormData] = useState<CategoryFormData>(
    initialData ? {
      name: initialData.name,
      description: initialData.description || "",
      icon: initialData.icon,
      is_active: initialData.is_active,
      slug: initialData.slug || "",
    } : initialFormData
  );

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value;
    const slug = slugify(name, { lower: true, strict: true });
    setFormData(prev => ({ ...prev, name, slug }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token) return;

    setLoading(true);
    setError(null);

    try {
      const url = initialData 
        ? `/api/categories/${initialData.id}` 
        : `/api/categories/`;
      
      const method = initialData ? "PUT" : "POST";

      // Prepare payload
      // API expects slug to be auto-generated by backend based on name
      const payload = {
        name: formData.name,
        description: formData.description,
        icon: formData.icon,
        is_active: formData.is_active,
      };

      const response = await fetchWithAuth(url, {
        method,
        body: JSON.stringify(payload),
      });

      if (response.ok) {
        router.push("/admin/categories");
        router.refresh();
      } else {
        const data = await response.json();
        setError(data.detail || "Error al guardar la categoría");
      }
    } catch (err) {
      console.error("Error saving category:", err);
      setError("Error de conexión");
    } finally {
      setLoading(false);
    }
  };

  const renderIcon = (iconName: string) => {
    const IconComponent = ICON_COMPONENTS[iconName];
    return IconComponent ? <IconComponent size={24} /> : null;
  };

  return (
    <div className="max-w-2xl mx-auto">
      <form onSubmit={handleSubmit} className="space-y-6">
        
        {/* Name */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
                <label className="text-sm font-medium text-gray-700">Nombre de la Categoría</label>
                <input
                    type="text"
                    required
                    className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all"
                    placeholder="Ej. Tecnología"
                    value={formData.name}
                    onChange={handleNameChange}
                />
            </div>
            <div className="space-y-2">
                <label className="text-sm font-medium text-gray-700">Slug</label>
                <input
                    type="text"
                    required
                    className="w-full px-4 py-2 rounded-xl border border-gray-200 bg-gray-50 text-gray-500 focus:outline-none transition-all"
                    placeholder="ej-tecnologia"
                    value={formData.slug}
                    readOnly
                />
            </div>
        </div>

        {/* Description */}
        <div className="space-y-2">
          <label className="text-sm font-medium text-gray-700">Descripción</label>
          <textarea
            className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all min-h-[100px]"
            placeholder="Descripción breve de la categoría..."
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
          />
        </div>

        {/* Icon Picker */}
        <div className="space-y-2">
          <label className="text-sm font-medium text-gray-700">Icono</label>
          <div className="grid grid-cols-6 sm:grid-cols-8 gap-2 p-4 bg-gray-50 rounded-xl border border-gray-100 max-h-48 overflow-y-auto">
            {AVAILABLE_ICONS.map((iconName) => (
              <button
                key={iconName}
                type="button"
                onClick={() => setFormData({ ...formData, icon: iconName })}
                className={cn(
                  "flex items-center justify-center p-2 rounded-lg transition-all hover:scale-105",
                  formData.icon === iconName 
                    ? "bg-primary text-white shadow-md shadow-primary/20 scale-105" 
                    : "bg-white text-gray-500 hover:text-primary border border-gray-200"
                )}
                title={iconName}
              >
                {renderIcon(iconName)}
              </button>
            ))}
          </div>
          {formData.icon && (
             <div className="flex items-center gap-2 text-sm text-gray-500 mt-2">
                <span>Icono seleccionado:</span>
                <span className="font-medium text-primary flex items-center gap-1">
                    {renderIcon(formData.icon)}
                    {formData.icon}
                </span>
                <button 
                    type="button" 
                    onClick={() => setFormData({...formData, icon: null})}
                    className="text-red-500 hover:text-red-700 ml-2 text-xs underline"
                >
                    Quitar
                </button>
             </div>
          )}
        </div>

        {/* Active Status */}
        <div className="flex items-center gap-3 p-4 bg-gray-50 rounded-xl border border-gray-100">
          <input
            type="checkbox"
            id="is_active"
            className="w-5 h-5 rounded text-primary focus:ring-primary border-gray-300"
            checked={formData.is_active}
            onChange={(e) => setFormData({ ...formData, is_active: e.target.checked })}
          />
          <label htmlFor="is_active" className="text-sm font-medium text-gray-700 cursor-pointer select-none">
            Categoría Activa
          </label>
        </div>

        {/* Error Message */}
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl flex items-center gap-2">
            <X size={20} />
            <span>{error}</span>
          </div>
        )}

        {/* Submit Button */}
        <button
          type="submit"
          disabled={loading}
          className="w-full bg-primary text-white py-3 rounded-xl hover:bg-primary/90 transition-colors shadow-sm shadow-primary/20 flex items-center justify-center gap-2 font-medium disabled:opacity-70 disabled:cursor-not-allowed"
        >
          {loading ? (
            <>
              <Loader2 className="animate-spin" size={20} />
              Guardando...
            </>
          ) : (
            <>
              <CheckCircle size={20} />
              {initialData ? "Actualizar Categoría" : "Crear Categoría"}
            </>
          )}
        </button>
      </form>
    </div>
  );
}
