var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/my-company/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8f45fc23._.js")
R.c("server/chunks/ssr/node_modules_next_dist_9266b807._.js")
R.c("server/chunks/ssr/_d4a63b14._.js")
R.c("server/chunks/ssr/[root-of-the-server]__36c803c8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_274ac3eb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/src_app_0c8a77b8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2fd24a5c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_07d69fb5._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_my-company_page_actions_22508fe2.js")
R.m(544205)
module.exports=R.m(544205).exports
