var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/orders/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__de06e410._.js")
R.c("server/chunks/ssr/node_modules_next_dist_9266b807._.js")
R.c("server/chunks/ssr/_f3da8212._.js")
R.c("server/chunks/ssr/[root-of-the-server]__36c803c8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_274ac3eb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/src_app_0c8a77b8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2fd24a5c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_ae1f9649._.js")
R.c("server/chunks/ssr/_next-internal_server_app_client_orders_page_actions_da7549c9.js")
R.m(564263)
module.exports=R.m(564263).exports
