var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/politicas-de-privacidad/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__823ccb6d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_9266b807._.js")
R.c("server/chunks/ssr/_6f0df5ea._.js")
R.c("server/chunks/ssr/[root-of-the-server]__36c803c8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_274ac3eb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/src_app_0c8a77b8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2fd24a5c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_politicas-de-privacidad_page_actions_d04ef048.js")
R.m(215333)
module.exports=R.m(215333).exports
